[package]
name = "imaginfo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0"
predicates = "2.0"
structopt = "0.3"
walkdir = "2"